# Generated by Django 4.2 on 2023-05-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciclador',
            name='credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
