# Generated by Django 4.2 on 2023-05-21 23:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade_pilha_AA', models.IntegerField(default=0)),
                ('quantidade_pilha_AAA', models.IntegerField(default=0)),
                ('quantidade_pilha_C', models.IntegerField(default=0)),
                ('quantidade_pilha_D', models.IntegerField(default=0)),
                ('quantidade_pilha_V9', models.IntegerField(default=0)),
                ('utilizado', models.BooleanField(default=False)),
                ('data_vencimento', models.DateTimeField()),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquina.maquina')),
            ],
        ),
    ]
