# Generated by Django 4.2 on 2023-06-13 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reciclador', '0002_reciclador_credito'),
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='preco_AA',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='preco_AAA',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='preco_C',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='preco_D',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='preco_V9',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='reciclador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reciclador.reciclador'),
        ),
    ]
