name: CI test

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: "3.11"

      - name: Run coverage test
        run: docker-compose run --rm --entrypoint "./scripts/test.sh" battery_service
