# Generated by Django 4.2 on 2023-05-21 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estabelecimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=50, null=True)),
                ('descricao', models.CharField(max_length=50, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=13)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('preco_AAA', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('preco_AA', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('preco_C', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('preco_D', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('preco_V9', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('quantidade_AAA', models.IntegerField(default=0)),
                ('quantidade_AA', models.IntegerField(default=0)),
                ('quantidade_C', models.IntegerField(default=0)),
                ('quantidade_D', models.IntegerField(default=0)),
                ('quantidade_V9', models.IntegerField(default=0)),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='maquina.endereco')),
                ('estabelecimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estabelecimento.estabelecimento')),
            ],
        ),
    ]
